"""
A Flask interface to read and write segmentation data on locally stored charters.
"""
from flask import Flask
from flask import render_template, request, jsonify, make_response, redirect, url_for
from pathlib import Path
import re
import json
from PIL import Image

# TODO:
#

app = Flask(__name__)

# SETTINGS
settings = {
        'scaling_factor': .5,
        'charter_img_suffix': '.img.jpg',
        'gt_segfile_suffix': '.lines.gt.json',
        'pred_segfile_suffix': '.lines.pred.json',
}

def lemmatize( p:Path):
    return re.sub(r'\..+', '',  p.name)


########## DATA ACCESS ################

def write_segmentation_file( page_data: dict, charter_id: str)->dict:
    """
    Write segmentation data into a JSON file.

    Args:
        segdata (dict): a dictionary
            {'page_wh': [<width>, <height>],
             'lines': [{'centerline': [[x1,y1], ...], 'boundary': [[x1,y1], ...]}, ...] }
    Returns:
        dict: if successful, an object with filename and size; otherwise an empty dictionary.

    """
    page_data.update( {
        "type": "centerlines",
        "text_direction": "horizontal-lr",
    })
    output_filename = '{}.lines.gt.json'.format(charter_id)
    returnValue = {}
    outputfile = None
    try:
        outputfile = open(output_filename, 'w')
        print( json.dumps(page_data, indent=4), file=outputfile)
        outputfile.close()
        returnValue = {'filename': output_filename, 'size': Path(output_filename).stat().st_size }
    except (IOError) as e:
        outputfile.close()
    return returnValue


def read_segmentation_file( segmentation_file: str ) -> dict:
    """
    Args:
        segmentation_file (str): a JSON file, Kraken-style
    Returns:
        dict: a segmentation dictionary.
    """
    seginfile = None
    returnValue = {}
    try:
        seginfile = open(segmentation_file, 'r') 
        returnValue = json.load( seginfile );
    except (IOError, FileNotFoundError) as e:
        pass
    finally:
        if seginfile is not None:
            seginfile.close();
    return returnValue;


# Listing all charters, with their existing segmentation meta-data

def get_charters():
    charters = { lemmatize(p):{'filename': str(p), 'gtsegfile': None} for p in Path('.').glob(f'*{settings["charter_img_suffix"]}') }
    for md5id in charters:
        gt_seg_filename = md5id + settings['gt_segfile_suffix']
        if Path( gt_seg_filename ).exists():
            charters[md5id]['hasGTData']=True
        pred_seg_filename = md5id + settings['pred_segfile_suffix']
        if Path( pred_seg_filename ).exists():
            charters[md5id]['hasPredData']=True
    return charters


#################### ROUTES ###############

@app.route('/')
def charters_choice():
    """ Display first charter in the list.
    """
    current = list(get_charters().keys())[0]
    return redirect(f'/{current}')

@app.get('/<charter_id>')
def charter_pick( charter_id:str):
    """ Display a charter image, as well as the list of charters.
    """
    charters = get_charters()
    with Image.open( charters[charter_id]['filename']) as img:
        print(charters[charter_id]['filename'])
        display_size = [int(d*settings['scaling_factor']) for d in img.size]
        print("display_size=",display_size)
        return render_template(
                'charters.html', 
                charters=charters, 
                charter_id=charter_id, 
                display_size=display_size
                )

@app.post('/export/<charter_id>')
def record_segmentation_data( charter_id:str ):
    """Export segmentation annotation to disk.
    """
    segmentation_data = request.get_json()
    ok = write_segmentation_file( segmentation_data, charter_id )
    resp = make_response( ok )
    return resp

@app.get('/import/<charter_id>')
def get_segmentation_gt( charter_id:str ):
    """ Import a mask generated by this application (for updates)
    """
    suffix = settings['pred_segfile_suffix'] if request.args.get( 'segtype' ) == 'pred' else settings['gt_segfile_suffix']
    segmentation_data = read_segmentation_file( '{}{}'.format( charter_id, suffix ))
    print(segmentation_data)
    return make_response( segmentation_data )


