from flask import Flask
from flask import render_template, request, jsonify, make_response, redirect, url_for
from pathlib import Path
import re
import json
from PIL import Image

# TODO:
#
#   + image W,H in segmentation data

app = Flask(__name__)

def lemmatize( p:Path):
    return re.sub(r'\..+', '',  p.name)

def write_segmentation_file( page_data: dict, charter_id: str)->dict:
    """
    Args:
        segdata (dict): a dictionary
            {'page_wh': [<width>, <height>],
             'lines': [{'centerline': [[x1,y1], ...], 'boundary': [[x1,y1], ...]}, ...] }

    """
    page_data.update( {
        "type": "centerlines",
        "text_direction": "horizontal-lr",
    })
    output_filename = '{}.lines.gt.json'.format(charter_id)
    returnValue = {}
    try:
        outputfile = open(output_filename, 'w')
        print( json.dumps(page_data, indent=4), file=outputfile)
        outputfile.close()
        returnValue = {'filename': output_filename, 'size': Path(output_filename).stat().st_size }
    except IOError as e:
        outputfile.close()
        returnValue = {'Abort': str(e) }
    finally:
        return returnValue

def read_segmentation_file( segmentation_file: str ) -> dict:
    with open(segmentation_file, 'r') as seginfile:
        segmentation_dict = json.load( seginfile )
        return segmentation_dict
    return {}

SCALING_FACTOR = .5
gt_segfile_suffix = '.lines.gt.json'
pred_segfile_suffix = '.lines.pred.json'

# Listing all charters, with their existing segmentation meta-data
charters = { lemmatize(p):{'filename': str(p), 'gtsegfile': None} for p in Path('.').glob('*.img.jpg') }
for md5id in charters:
    gt_seg_filename = md5id + gt_segfile_suffix
    if Path( gt_seg_filename ).exists():
        charters[md5id]['hasGTData']=True
    pred_seg_filename = md5id + pred_segfile_suffix
    if Path( pred_seg_filename ).exists():
        charters[md5id]['hasPredData']=True
print( charters)

@app.route('/')
def charters_choice():
    current = list(charters.keys())[0]
    return redirect(f'/{current}')

@app.get('/<charter_id>')
def charter_pick( charter_id:str):
    with Image.open( charters[charter_id]['filename']) as img:
        print(charters[charter_id]['filename'])
        return render_template(
                'charters.html', 
                charters=charters, 
                charter_id=charter_id, 
                charter_size=[d*SCALING_FACTOR for d in img.size],
                )

@app.post('/export/<charter_id>')
def record_segmentation_data( charter_id:str ):
    segmentation_data = request.get_json()
    ok = write_segmentation_file( segmentation_data, charter_id )
    resp = make_response( ok )
    return resp

@app.get('/import/<charter_id>')
def get_segmentation_gt( charter_id:str ):
    """
    Import a mask generated by this application (for updates)
    """
    segmentation_data = read_segmentation_file( '{}{}'.format( charter_id, gt_segfile_suffix ))
    return make_response( segmentation_data )


